#ifndef DW_CONFIG_H
#define DW_CONFIG_H

#define DW_DELTA_TIME 10
#define DW_OPENGL_MAJOR_VERSION 3
#define DW_OPENGL_MINOR_VERSION 3
#define DW_DEPTH_SIZE 24
#define DW_DOUBLEBUFFER 1


#define DW_PLANET_MIN_RADIUS 100.0
#define DW_PLANET_MAX_RADIUS 400.0
#define DW_PLANET_RADIUS_DIFF 15.0

#endif
