#ifndef DW_CONFIG_H
#define DW_CONFIG_H

#define DW_DELTA_TIME 10
#define DW_OPENGL_MAJOR_VERSION 3
#define DW_OPENGL_MINOR_VERSION 3
#define DW_DEPTH_SIZE 24
#define DW_DOUBLEBUFFER 1


#define DW_MIN_PLANET_RADIUS 10.0
#define DW_MAX_PLANET_RADIUS 100.0

#endif
